USE LANCER;
GO

CREATE TABLE pilot.License (
	LicenseID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_License_LicenseID PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	[Rank] TINYINT NOT NULL
);
GO

/*
INSERT INTO pilot.License (
	Name,
	[Rank]
)
VALUES
('GMS Standard', 1),
('IPS-N Blackbeard', 1),
('IPS-N Blackbeard', 2),
('IPS-N Blackbeard', 3),
('IPS-N Drake', 1),
('IPS-N Drake', 2),
('IPS-N Drake', 3),
('IPS-N Lancaster', 1),
('IPS-N Lancaster', 2),
('IPS-N Lancaster', 3),
('IPS-N Nelson', 1),
('IPS-N Nelson', 2),
('IPS-N Nelson', 3),
('IPS-N Raleigh', 1),
('IPS-N Raleigh', 2),
('IPS-N Raleigh', 3),
('IPS-N Tortuga', 1),
('IPS-N Tortuga', 2),
('IPS-N Tortuga', 3),
('IPS-N Vlad', 1),
('IPS-N Vlad', 2),
('IPS-N Vlad', 3),
('SSC Black Witch', 1),
('SSC Black Witch', 2),
('SSC Black Witch', 3),
('SSC Death''s Head', 1),
('SSC Death''s Head', 2),
('SSC Death''s Head', 3),
('SSC Dusk Wing', 1),
('SSC ', 2),
('SSC ', 3),
('SSC Metalmark', 1),
('SSC Metalmark', 2),
('SSC Metalmark', 3),
('SSC Monarch', 1),
('SSC Monarch', 2),
('SSC Monarch', 3),
('SSC Mourning Cloak', 1),
('SSC Mourning Cloak', 2),
('SSC Mourning Cloak', 3),
('SSC Swallowtail', 1),
('SSC Swallowtail', 2),
('SSC Swallowtail', 3),
('HORUS Balor', 1),
('HORUS Balor', 2),
('HORUS Balor', 3),
('HORUS Goblin', 1),
('HORUS Goblin', 2),
('HORUS Goblin', 3),
('HORUS Gorgon', 1),
('HORUS Gorgon', 2),
('HORUS Gorgon', 3),
('HORUS Hydra', 1),
('HORUS Hydra', 2),
('HORUS Hydra', 3),
('HORUS Manticore', 1),
('HORUS Manticore', 2),
('HORUS Manticore', 3),
('HORUS Minotaur', 1),
('HORUS Minotaur', 2),
('HORUS Minotaur', 3),
('HORUS Pegasus', 1),
('HORUS Pegasus', 2),
('HORUS Pegasus', 3),
('HA Barbarossa', 1),
('HA Barbarossa', 2),
('HA Barbarossa', 3),
('HA Genghis', 1),
('HA Genghis', 2),
('HA Genghis', 3),
('HA Iskander', 1),
('HA Iskander', 2),
('HA Iskander', 3),
('HA Napoleon', 1),
('HA Napoleon', 2),
('HA Napoleon', 3),
('HA Saladin', 1),
('HA Saladin', 2),
('HA Saladin', 3),
('HA Sherman', 1),
('HA Sherman', 2),
('HA Sherman', 3),
('HA Tokugawa', 1),
('HA Tokugawa', 2),
('HA Tokugawa', 3),
('SSC Atlas', 1),
('SSC Atlas', 2),
('SSC Atlas', 3),
('IPS-N Caliban', 1),
('IPS-N Caliban', 2),
('IPS-N Caliban', 3),
('HORUS Kobold', 1),
('HORUS Kobold', 2),
('HORUS Kobold', 3),
('HORUS Lich', 1),
('HORUS Lich', 2),
('HORUS Lich', 3),
('HA Sunzi', 1),
('HA Sunzi', 2),
('HA Sunzi', 3),
('IPS-N Zheng', 1),
('IPS-N Zheng', 2),
('IPS-N Zheng', 3)
*/