USE LANDER;
GO

CREATE TABLE pilot.Talent (
	TalentID INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Talent_TalentID PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	[Rank] TINYINT NOT NULL,
	RankName VARCHAR(50) NOT NULL,
	Description VARCHAR(500) NOT NULL
);
GO

/*
INSERT INTO pilot.Talent (
	Name,
	[Rank],
	RankName,
	Description
)
VALUES
('Ace', 1, 'Acrobatics', 'While(Flying): If SaveCheckType == Agility, Acc +1, If Hostile.Attack() == Miss, May(Reaction(Fly 2))'),
('Ace', 2, 'Afterburners', 'If Move.Boost(), May(Move 1d6 && Self.Heat(Move/2))'),
('Ace', 3, 'Supersonic', ''),
('Bonded', 1, 'I''m Your Huckleberry', ''),
('Bonded', 2, 'Sundance', ''),
('Bonded', 3, 'Cover Me!', ''),
('Brawler', 1, 'Hold and Lock', ''),
('Brawler', 2, 'Sledgehammer', ''),
('Brawler', 3, 'Knockout Blow', ''),
('Brutal', 1, 'Predator', ''),
('Brutal', 2, 'Cull the Herd', ''),
('Brutal', 3, 'Relentless', ''),
('Crack Shot', 1, 'Stable, Steady', ''),
('Crack Shot', 2, 'Zero In', ''),
('Crack Shot', 3, 'Watch This', ''),
('Centimane', 1, 'Ten Thousand Teeth', ''),
('Centimane', 2, 'Expose Weakness', ''),
('Centimane', 3, 'Tidal Suppression', ''),
('Combined Arms', 1, 'Shield of Blades', ''),
('Combined Arms', 2, 'CQB-Trained', ''),
('Combined Arms', 3, 'Storm of Violence', ''),
('Duelist', 1, 'Man-at-Arms', ''),
('Duelist', 2, 'Blademaster', ''),
('Duelist', 3, 'Unstoppable', ''),
('Drone Commander', 1, 'Shepherd', ''),
('Drone Commander', 2, 'Energized Swarm', ''),
('Drone Commander', 3, 'Invigorate', ''),
('Engineer', 1, 'Prototype', ''),
('Engineer', 2, 'Revision', ''),
('Engineer', 3, 'Final Draft', ''),
('Executioner', 1, 'Backswing Cut', ''),
('Executioner', 2, 'Wide Arc Cleave', ''),
('Executioner', 3, 'No Escape', ''),
('Exemplar', 1, 'Honorable Challenge', ''),
('Exemplar', 2, 'Punishment', ''),
('Exemplar', 3, 'To the Death', ''),
('Gunslinger', 1, 'Opening Argument', ''),
('Gunslinger', 2, 'From the Hip', ''),
('Gunslinger', 3, 'I Kill with My Heart', ''),
('Grease Monkey', 1, 'Unsanctioned Capacity Upgrade', ''),
('Grease Monkey', 2, 'Machine Bond', ''),
('Grease Monkey', 3, 'Friends in High Places', ''),
('Hacker', 1, 'Snow_Crash', ''),
('Hacker', 2, 'Safe_Cracker', ''),
('Hacker', 3, 'Last Argument of Kings', ''),
('Heavy Gunner', 1, 'Covering Fire', ''),
('Heavy Gunner', 2, 'Hammerbeat', ''),
('Heavy Gunner', 3, 'Bracketing Fire', ''),
('Hunter', 1, 'Lunge', ''),
('Hunter', 2, 'Knife Juggler', ''),
('Hunter', 3, 'Disdainful Blade', ''),
('Infiltrator', 1, 'Prowl', ''),
('Infiltrator', 2, 'Ambush', ''),
('Infiltrator', 3, 'Mastermind', ''),
('Juggernaut', 1, 'Momentum', ''),
('Juggernaut', 2, 'Kinetic Mass Transfer', ''),
('Juggernaut', 3, 'Unstoppable Force', ''),
('Leader', 1, 'Field Commander', ''),
('Leader', 2, Open Channels'', ''),
('Leader', 3, 'Inspiring Presence', ''),
('Nuclear Cavalier', 1, 'Aggressive Heat Bleed', ''),
('Nuclear Cavalier', 2, 'Fusion Hemorrhage', ''),
('Nuclear Cavalier', 3, 'Here, Catch!', ''),
('Siege Specialist', 1, 'Jackhammer', ''),
('Siege Specialist', 2, 'Impact', ''),
('Siege Specialist', 3, 'Collateral Damage', ''),
('Skirmisher', 1, 'Integrated Chaff Launchers', ''),
('Skirmisher', 2, 'Lockbreaker', ''),
('Skirmisher', 3, 'Weave', ''),
('Spotter', 1, 'Particularize', ''),
('Spotter', 2, 'Panopticon', ''),
('Spotter', 3, 'Bentham/Foucault Elimination', ''),
('Stormbringer', 1, 'Seismic Deluge', ''),
('Stormbringer', 2, 'Stormbending', ''),
('Stormbringer', 3, 'Torrent', ''),
('Tactician', 1, 'Opportunist', ''),
('Tactician', 2, 'Solar Backdrop', ''),
('Tactician', 3, 'Overlapping Fire', ''),
(Technophile'', 1, 'Servant Fragment', ''),
('Technophile', 2, 'Student Fragment', ''),
('Technophile', 3, 'Enlightenment', ''),
('Vanguard', 1, 'Handshake Etiquette', ''),
('Vanguard', 2, 'See-Through Seeker', ''),
('Vanguard', 3, 'Semper Vigilo', ''),
('Walking Armory', 1, 'Armament', ''),
('Walking Armory', 2, 'Expanded Portfolio', ''),
('Walking Armory', 3, 'Efficiency', ''),
*/